site_name: Splunk Data Drivers
repo_name: splunk/f1-simulator
repo_url: https://github.com/splunk/f1-simulator
site_url: https://splunk.github.io/f1-simulator
edit_uri: edit/main/docs
theme:
  name: material 
  palette:
    scheme: slate
    primary: orange
    accent: amber
  icon:
    logo: simple/splunk 
  favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    #- toc.integrate
  custom_dir: material/overrides
  font:
    code: Roboto Mono
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: index.md
  - F1 2025 Collector:
    - Overview: f1-2025/index.md
    - Docker Setup (Self-Hosted): f1-2025/docker-setup.md
    - Using the Collector:
      - Overview: f1-2025/configuration.md
      - Controller Configuration: f1-2025/controller-config.md
      - Managing Collectors: f1-2025/managing-collectors.md
    - Game Telemetry Setup: f1-2025/telemetry.md
    - Dashboards: f1-2025/dashboards.md
  - F1 2025 Event Guide:
    - Game Configuration:
        - Start Grand Prix: event_guide/grand-prix.md
        - Assists: event_guide/assists.md
        - Rules & Flags: event_guide/rules.md
        - Weekend Structure: event_guide/structure.md
        - Simulation Settings: event_guide/simulation-settings.md
        - Weather and Time of Day: event_guide/weather.md
        - Go Racing: event_guide/go-racing.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/github
      link: https://github.com/splunk
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/splunk/
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/splunkinc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/splunkvideos

  generator: false

plugins:
  - mkdocs-video

extra_css:
  - stylesheets/custom.css

copyright: Copyright &copy; 2025 - Splunk Inc.
