site_name: Splunk Data Drivers
repo_name: splunk/f1-simulator
repo_url: https://github.com/splunk/f1-simulator
edit_uri: edit/main/docs
theme:
  name: material 
  palette:
    scheme: slate
    primary: orange
    accent: amber
  icon:
    logo: simple/splunk 
  favicon: favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    #- toc.integrate
  custom_dir: material/overrides
  font:
    code: Roboto Mono
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: index.md
  - F1 2023 Collector:
    - Pre-requisites: f1_2023/index.md
    - Setup: f1_2023/setup.md
    - Accessing the Web Interface: f1_2023/ui.md
    - Configuration: f1_2023/configuration.md
    #- Game Configuration: f1_2023/game.md
    - Dashboards: f1_2023/dashboards.md
  - F1 2024 Collector:
    - Pre-requisites: f1_2024/index.md
    - Setup: f1_2024/setup.md
    - Accessing the Web Interface: f1_2024/ui.md
    - Configuration: f1_2024/configuration.md
    - Dashboards: f1_2024/dashboards.md
  - F1 2023 Event Guide:
    - Game Configuration:
        - Telemetry: event_guide/telemetry.md
        - Start Grand Prix: event_guide/grand-prix.md
        - Assists: event_guide/assists.md
        - Rules & Flags: event_guide/rules.md
        - Weekend Structure: event_guide/structure.md
        - Simulation Settings: event_guide/simulation-settings.md
        - Weather and Time of Day: event_guide/weather.md
        - Go Racing: event_guide/go-racing.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/github
      link: https://github.com/splunk
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/splunk/
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/splunkinc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/splunkvideos

  generator: false

plugins:
  - mkdocs-video

extra_css:
  - stylesheets/custom.css

copyright: Copyright &copy; 2024 - Splunk Inc.
